server:
  port: 8080

spring:
  application:
    name: bff-pedidos360
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID:common}/v2.0
          audiences: ${AZURE_API_AUDIENCE:api://99523fae-980a-4c64-bde4-26e92c7376e9}

pedidos360:
  security:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}
  services:
    productos-url: ${PRODUCTOS_URL:http://localhost:8081}
    clientes-url: ${CLIENTES_URL:http://localhost:8082}
    pedidos-url: ${PEDIDOS_URL:http://localhost:8083}
    notifications-url: ${NOTIFICATIONS_URL:http://localhost:8084}
    rabbit-admin-url: ${RABBIT_ADMIN_URL:http://localhost:8085}
    auditoria-url: ${AUDITORIA_URL:http://localhost:8086}

management:
  endpoints:
    web:
      exposure:
        include: health,info
